#
# Configuration for GitHub-based CI, based on the stock GitHub Rust config.
#
name: Rust

on: [ push, pull_request ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, macos-10.15, windows-2019 ]
        toolchain: [ "1.40", stable, nightly-2021-09-03 ]
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
    - name: Install Toolchain
    # actions-rs/toolchain@v1.0.6
      uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
      with:
          toolchain: ${{ matrix.toolchain }}
          override: true
    - name: Report cargo version
      run: cargo +${{ matrix.toolchain }} --version
    - name: Build
      run: cargo +${{ matrix.toolchain }} build --all-targets --verbose
    - name: Run tests
      run: cargo +${{ matrix.toolchain }} test --verbose
    - name: Show runtime dependencies (Linux only)
      if: runner.os == 'Linux'
      run: find target/debug/deps -name 'smoke-*' -not -name '*.d' | xargs readelf -d
